import LegalLayout from './LegalLayout';
import { AlertTriangle, HardHat, CheckCircle2, FileText, Compass, DollarSign, Ruler, Building } from 'lucide-react';

export default function DisclaimerPage() {
  const substitutions = [
    {
      icon: HardHat,
      title: 'Licensed Professional Engineers',
      desc: 'Civil, structural, geotechnical, and environmental engineers licensed in your project jurisdiction who bear statutory design liability.',
    },
    {
      icon: Building,
      title: 'Registered Architects',
      desc: 'Architectural designers responsible for spatial egress, fire safety ratings, building envelope compliance, and local zoning adherence.',
    },
    {
      icon: DollarSign,
      title: 'Professional Quantity Surveyors',
      desc: 'Cost consultants and certified estimators who calculate market-rate material pricing, regional labor rates, and contractual contingencies.',
    },
    {
      icon: Compass,
      title: 'Licensed Land Surveyors',
      desc: 'Professional land surveyors who conduct legal boundary surveys, control network establishment, and certified site topographic maps.',
    },
    {
      icon: FileText,
      title: 'Approved Project Drawings',
      desc: 'Contract-specific architectural, structural, and MEP engineering drawings that bear formal revision approvals and professional stamps.',
    },
    {
      icon: Ruler,
      title: 'Contract Specifications & Tender Documents',
      desc: 'Project-specific technical specifications, employer requirements, testing standards, and site contract conditions.',
    },
  ];

  const toc = [
    { id: 'educational-nature', label: '1. Educational & Planning Reference Only' },
    { id: 'not-a-substitute', label: '2. What CivilMath Does Not Replace' },
    { id: 'calculation-assumptions', label: '3. Engineering Assumptions & Nominal Values' },
    { id: 'user-verification', label: '4. User Verification Responsibilities' },
    { id: 'jurisdiction-codes', label: '5. Regional Building Codes & Standards' },
    { id: 'liability-limitation', label: '6. Limitation of Liability' },
    { id: 'contact-engineering', label: '7. Engineering Clarifications & Corrections' },
  ];

  return (
    <LegalLayout
      title="Engineering Disclaimer"
      badge="CivilMath Professional Trust"
      lastUpdated="September 2026"
      summary="CivilMath is an educational calculation and engineering reference platform. All formulas, schedules, and calculators provide preliminary estimates and educational demonstrations only. CivilMath is never a substitute for a licensed Professional Engineer (PE/CEng), approved contract drawings, or local building regulations. All outputs must be verified before execution."
      toc={toc}
    >
      {/* 1. Educational Nature */}
      <section id="educational-nature" className="space-y-3">
        <h2 className="text-xl font-bold text-[#20231F] dark:text-[#EAE7E0]">
          1. Educational &amp; Planning Reference Only
        </h2>
        <p>
          CivilMath (<a href="https://civilmath.com" className="text-[#657565] dark:text-[#9FB19F] underline">civilmath.com</a>) provides educational civil engineering information, interactive calculators, formulas, bar bending schedules, design examples, and construction-related references.
        </p>
        <p>
          The mission of CivilMath is to make practical civil engineering theory and numerical workflows transparent, understandable, and accessible to students, practicing engineers, site supervisors, and quantity estimators. However, our digital tools are designed solely for preliminary study, order-of-magnitude estimates, and independent academic cross-checking.
        </p>
        <div className="p-4 rounded-xl bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-900/50 flex items-start gap-3 text-amber-900 dark:text-amber-200 text-xs sm:text-sm">
          <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <strong className="block font-bold">No Engineering Stamp or Construction Instruction:</strong>
            <p className="m-0 leading-relaxed text-xs">
              Outputs generated by CivilMath do <strong>not</strong> constitute a signed design, certified construction instruction, stamped engineering document, building permit application, or professional engineering guarantee.
            </p>
          </div>
        </div>
      </section>

      {/* 2. What CivilMath Does Not Replace */}
      <section id="not-a-substitute" className="space-y-4">
        <h2 className="text-xl font-bold text-[#20231F] dark:text-[#EAE7E0]">
          2. What CivilMath Does Not Replace
        </h2>
        <p>
          Civil engineering projects involve critical structural safety, life-safety requirements, environmental factors, and substantial financial investments. CivilMath must <strong>never</strong> be treated as a substitute for:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
          {substitutions.map((item) => {
            const Icon = item.icon;
            return (
              <div
                key={item.title}
                className="p-4 rounded-xl bg-[#FAF9F6] dark:bg-[#1E221E] border border-[#D8D0C2] dark:border-[#333C33] space-y-1.5"
              >
                <div className="flex items-center gap-2">
                  <div className="w-7 h-7 rounded-lg bg-[#657565]/10 text-[#657565] dark:text-[#9FB19F] flex items-center justify-center shrink-0">
                    <Icon className="w-4 h-4" />
                  </div>
                  <h3 className="text-xs font-bold text-[#20231F] dark:text-[#EAE7E0] m-0">
                    {item.title}
                  </h3>
                </div>
                <p className="text-xs text-[#7B8978] leading-relaxed m-0 pl-9">
                  {item.desc}
                </p>
              </div>
            );
          })}
        </div>

        <p className="text-xs sm:text-sm text-[#555C55] dark:text-[#A4B2A4] mt-2">
          Furthermore, CivilMath cannot replace site-specific geotechnical soil investigation reports, chemical laboratory water and aggregate testing, or municipal building code official inspections.
        </p>
      </section>

      {/* 3. Calculation Assumptions */}
      <section id="calculation-assumptions" className="space-y-3">
        <h2 className="text-xl font-bold text-[#20231F] dark:text-[#EAE7E0]">
          3. Engineering Assumptions &amp; Nominal Values
        </h2>
        <p>
          Every civil engineering calculation is predicated on idealized physical boundary conditions and standard material coefficients. In our tools:
        </p>
        <ul className="list-disc pl-5 space-y-1.5 text-xs sm:text-sm">
          <li>
            <strong>Material Densities:</strong> Concrete density is typically modeled at nominal reinforced concrete values (e.g., 2400 kg/m³ or 150 lb/ft³). Actual field density varies with aggregate type, air entrainment, and slump.
          </li>
          <li>
            <strong>Rebar Unit Weights:</strong> Steel rebar weights are computed from nominal theoretical diameters via the standard formula <code className="text-xs font-mono bg-[#EAE7E0] dark:bg-[#2E362E] px-1 py-0.5 rounded">d²/162 kg/m</code>. Rolling mill tolerances permit slight dimensional variances under ASTM A615 and BS 4449.
          </li>
          <li>
            <strong>Structural Idealizations:</strong> Beam and column analysis models assume idealized pinned, fixed, or roller supports, linear elastic material response, and small-displacement theory unless explicitly noted.
          </li>
          <li>
            <strong>Geotechnical Parameters:</strong> Bearing capacity formulations (Terzaghi, Meyerhof, Vesic) assume uniform, semi-infinite soil strata. Real sites feature layered stratigraphy, fluctuating water tables, and localized fissures that require geotechnical borehole analysis.
          </li>
        </ul>
      </section>

      {/* 4. User Verification Responsibilities */}
      <section id="user-verification" className="space-y-3">
        <h2 className="text-xl font-bold text-[#20231F] dark:text-[#EAE7E0]">
          4. User Verification Responsibilities
        </h2>
        <p>
          Before any concrete pour, rebar order placement, excavation work, or foundation layout is initiated, users are strictly required to independently verify:
        </p>
        <ul className="list-disc pl-5 space-y-1 text-xs sm:text-sm">
          <li>All input dimensions, clear cover allowances, hook lengths, and bend deductions.</li>
          <li>Reinforcement lap splice lengths, anchorage depths, and development lengths according to applicable code criteria.</li>
          <li>Site soil bearing capacity against certified geotechnical borehole logs.</li>
          <li>Material waste allowances (typically 3–5% for reinforcement, 2–5% for ready-mix concrete).</li>
          <li>Calculated quantities against contractual Bill of Quantities (BOQ) line items and tender specifications.</li>
        </ul>
      </section>

      {/* 5. Regional Codes & Standards */}
      <section id="jurisdiction-codes" className="space-y-3">
        <h2 className="text-xl font-bold text-[#20231F] dark:text-[#EAE7E0]">
          5. Regional Building Codes &amp; Standards
        </h2>
        <p>
          CivilMath calculator presets reference widely recognized international standards, including:
        </p>
        <ul className="list-disc pl-5 space-y-1 text-xs sm:text-sm">
          <li><strong>ACI 318:</strong> Building Code Requirements for Structural Concrete (American Concrete Institute).</li>
          <li><strong>Eurocode 2 (EN 1992):</strong> Design of Concrete Structures (European Committee for Standardization).</li>
          <li><strong>IS 456 &amp; IS 1786:</strong> Plain and Reinforced Concrete Code of Practice (Bureau of Indian Standards).</li>
          <li><strong>BS 8666 &amp; BS 8110:</strong> Scheduling, dimensioning, bending, and cutting of steel reinforcement.</li>
        </ul>
        <p>
          However, national annexes, seismic zoning maps, local wind load coefficients, exposure classes (e.g., severe marine or sulfate exposure), and municipal bylaws frequently enforce stricter safety factors than generic code baselines. Users must confirm that calculations comply with the specific jurisdiction governing the job site.
        </p>
      </section>

      {/* 6. Limitation of Liability */}
      <section id="liability-limitation" className="space-y-3">
        <h2 className="text-xl font-bold text-[#20231F] dark:text-[#EAE7E0]">
          6. Comprehensive Limitation of Liability
        </h2>
        <div className="p-4 rounded-xl bg-[#FAF9F6] dark:bg-[#1E221E] border border-[#D8D0C2] dark:border-[#333C33] text-xs sm:text-sm space-y-2">
          <p className="font-bold text-[#20231F] dark:text-[#EAE7E0] m-0">
            CivilMath Disclaims All Liability for Construction Outcomes:
          </p>
          <p className="leading-relaxed m-0 text-xs text-[#555C55] dark:text-[#C5D0C5]">
            CivilMath, its creators, authors, developers, and partners make no representations or warranties of any kind regarding the completeness, accuracy, reliability, or suitability of the information and tools provided.
          </p>
          <p className="leading-relaxed m-0 text-xs text-[#555C55] dark:text-[#C5D0C5]">
            Under no circumstances shall CivilMath be liable for any direct, indirect, special, incidental, punitive, or consequential damages—including structural failure, personal injury, property loss, construction downtime, contractor claims, or material shortages—arising directly or indirectly from the use of, or reliance upon, any calculator output or technical content on this site.
          </p>
        </div>
      </section>

      {/* 7. Engineering Corrections */}
      <section id="contact-engineering" className="space-y-3">
        <h2 className="text-xl font-bold text-[#20231F] dark:text-[#EAE7E0]">
          7. Technical Corrections &amp; Formula Inquiries
        </h2>
        <p>
          CivilMath is committed to mathematical transparency and academic rigor. If you identify an error in a formula derivation, find a discrepancy in a rebar bend deduction calculation, or would like to propose an updated code equation, we welcome your peer review.
        </p>
        <p>
          Please reach out to our engineering team with technical references, code citations, and derivation notes:
        </p>
        <div className="p-4 rounded-xl bg-white dark:bg-[#252B25] border border-[#D8D0C2] dark:border-[#384238] space-y-1 font-mono text-xs">
          <div><strong>Technical Desk:</strong> <a href="mailto:support@civilmath.com" className="text-[#657565] underline">support@civilmath.com</a></div>
          <div><strong>Subject Line:</strong> Technical Review / Formula Discrepancy</div>
          <div><strong>Contact Page:</strong> <a href="/contact" className="text-[#657565] underline font-sans">civilmath.com/contact</a></div>
        </div>
      </section>
    </LegalLayout>
  );
}
